/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter2;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.util.Scanner;


public class App {
    public static int callFile(String path) {
        Scanner scanner = null;
        int line = 0;
        int ErrorCount = 0;
        try {
            scanner = new Scanner(new BufferedReader(new FileReader(path)));

            while (scanner.hasNextLine()){
                line++;
                String readMe = scanner.nextLine();
                if (readMe.length()>0 && !(readMe.endsWith(";") || readMe.endsWith("{") || readMe.endsWith("}") || readMe.contains("if") || readMe.contains("else"))){
                    ErrorCount++;
                    System.out.println("Line " + line + ": Missing semicolon.");
                }
            }
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }
        System.out.println("Line " + ErrorCount);
        return ErrorCount;
    }

    public static void main(String[] args) {
        callFile("app/src/main/resources/gates.js");

    }
}
