/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter2;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void callFileTest (){

        String path1 = "app/src/test/resources/oneError.js";
        ArrayList<String>  test1=App.callFile(path1);
        ArrayList<String> correctAnswer1 = new ArrayList<>();
        correctAnswer1.add("Line 2: Missing semicolon.");
        assertEquals(correctAnswer1,test1);


        String path2 = "app/src/test/resources/empty.js";
        ArrayList<String>  test2=App.callFile(path2);
        ArrayList<String> correctAnswer2 = new ArrayList<>();
        assertEquals(correctAnswer2,test2);

        String path3 = "app/src/test/resources/fewErrors.js";
        ArrayList<String>  test3=App.callFile(path3);
        ArrayList<String> correctAnswer3 = new ArrayList<>();
        correctAnswer3.add("Line 2: Missing semicolon.");
        correctAnswer3.add("Line 4: Missing semicolon.");
        correctAnswer3.add("Line 6: Missing semicolon.");
        correctAnswer3.add("Line 8: Missing semicolon.");
        assertEquals(correctAnswer2,test2);

        String path4 = "app/src/test/resources/NoErrorsFile.js";
        ArrayList<String>  test4=App.callFile(path4);
        ArrayList<String> correctAnswer4 = new ArrayList<>();
        assertEquals(correctAnswer4,test4);


        String path5 = "app/src/test/resources/gates.js";
        ArrayList<String>  test5=App.callFile(path5);
        ArrayList<String> correctAnswer5 = new ArrayList<>();
        correctAnswer5.add("Line 2: Missing semicolon.");
        correctAnswer5.add("Line 3: Missing semicolon.");
        correctAnswer5.add("Line 4: Missing semicolon.");
        correctAnswer5.add("Line 5: Missing semicolon.");
        correctAnswer5.add("Line 6: Missing semicolon.");
        correctAnswer5.add("Line 7: Missing semicolon.");
        correctAnswer5.add("Line 8: Missing semicolon.");
        correctAnswer5.add("Line 9: Missing semicolon.");

        assertEquals(correctAnswer5,test5);
    }
}
