/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
/*
package basiclibrary;

import org.junit.Test;

import java.util.Arrays;

import static java.util.function.Predicate.not;
import static org.junit.Assert.*;


 */
class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }

    @Test public void testRoll() {
        int[] testArray = new int[3];
        assertEquals(testArray.length, Library.roll(3).length);
    }

    @Test public void testContainsDuplicates() {
        int[] testArray = {1, 2, 3, 3};
        int[] testArrayTwo = {5, 4, 3, 2, 1, 0};

        assertTrue(Library.containsDuplicates(testArray));
        assertFalse(Library.containsDuplicates(testArrayTwo));
    }

    @Test public void testAverage() {
        int[] testArray = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10};
        double control = 5.5;
        assertEquals(control, Library.average(testArray), .1);
    }

    @Test public void testTally() {
        List<String> votes = new ArrayList<>();
        votes.add("Bush");
        votes.add("Bush");
        votes.add("Bush");
        votes.add("Shrub");
        votes.add("Hedge");
        votes.add("Shrub");
        votes.add("Bush");
        votes.add("Hedge");
        votes.add("Bush");
        assertEquals("Bush", Library.tally(votes));
    }
}