/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;


class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }


    @Test public void testRoll() {
        int[] testArray = new int[3];
        assertEquals(testArray.length, Library.roll(3).length);
    }

    @Test public void testContainsDuplicates() {
        int[] testArray = {1, 2, 3, 3};
        int[] testArrayTwo = {5, 4, 3, 2, 1, 0};

        assertTrue(Library.containsDuplicates(testArray));
        assertFalse(Library.containsDuplicates(testArrayTwo));
    }

    @Test public void testAverage() {
        int[] testArray = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10};
        double control = 5.5;
        assertEquals(control, Library.average(testArray), .1);
    }

    @Test public void testLowestAverage() {
        int[][] weeklyMonthTemperatures = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57},
                {-4, 3, 3, 5, 0, -2, -4}
        };
        int[] control = {-4, 3, 3, 5, 0, -2, -4};
        assertArrayEquals(control, Library.lowestAverage(weeklyMonthTemperatures));
    }

}