/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    public static void main(String[] args) {
        roll(4);
        int[] arr = {5,5,10,11,9,3,11};
        containsDuplicates(arr);
    }

    public static int[] roll(int n) {
        int[] r = new int[n];
        for (int i = 0; i < n; i++) {
            int random = (int) Math.ceil(Math.random() * 6);
            r[i] = random;
        }
        return r;
    }

    public static boolean containsDuplicates(int[] arr) {
        boolean duplicate = false;
        for (int i = 0; i < arr.length; i++) {
            for (int j = 1; j < i; j++) {
                if (arr[j] == arr[i]) {
                    duplicate = true;
                }
            }
        }
        return duplicate;
    }

    public static double average(int[] arr) {
        double sum = 0;
        for (int i = 0; i < arr.length; i++) {
            sum += arr[i];
        }
        return sum / arr.length;
    }
    public static int[] lowestAverage(int[][] arrays) {
        int[] lowest = arrays[0];
        double lowestAvg = average(lowest);
        for (int[] set : arrays) {
            if (average(set) < lowestAvg) {
                lowest = set;
            }
        }
        return lowest;
    }
}
