/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

public class Library {
    public static void main(String[] args) {
        System.out.println("Test =======> Pizza Restaurant");
        Restaurant pizzaRest = new Restaurant("hot pizza", 100, 4);
        //System.out.println(pizzaRest.toString());

        Review review1 = new Review("delicious" , "Rawzi" , 2);
        Review review2 = new Review("good" , "Mohammed" , 4);
        Review review3 = new Review("bad" , "Rawzi" , 5);
        System.out.println(review1);

        System.out.println(review1.toString());
//        pizzaRest.addReview(review1);
//        pizzaRest.addReview(review2);
//        pizzaRest.addReview(review3);
//        System.out.println(pizzaRest.toString());
    }
}
