/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

public class Library {
    public static void main(String[] args) {
        System.out.println("Test =======> Pizza Restaurant");
        Restaurant();
    }
    public static void Restaurant(){

        Restaurant pizzaRest = new Restaurant("hot pizza", 100, 4);
        //add reviews
        Review firstReview = new Review("delicious" ,"John" ,5);
        Review sceReview = new Review("very good" ,"Rami" ,4);
        Review thirdReview = new Review("bad" ,"Sara" ,1);


        pizzaRest.addReview(firstReview);
        pizzaRest.addReview(sceReview);
        pizzaRest.addReview(thirdReview);

        pizzaRest.getStars();

        System.out.println(pizzaRest.toString());
    }
}
