/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

class AppTest {

    Restaurant restaurant1 = new Restaurant("Pizza", 109.36, 5);
    Review review1 = new Review("Delicious","Omar",5);
    Review review2 = new Review("good","Duaa",3);
    Review review3 = new Review("not bad","Rawzi",2);

    @Test
    public void testToStringRestaurant(){

        assertEquals("Restaurant{name='Pizza', numOfStars=5.0, price=109.36, reviews=[]}",restaurant1.toString());
    }

    @Test
    public void testAddReview() {

        restaurant1.addReview(review1);
        assertEquals(1, restaurant1.getReviews().size());

        restaurant1.addReview(review2);
        assertEquals(2, restaurant1.getReviews().size());

        restaurant1.addReview(review3);
        assertEquals(3, restaurant1.getReviews().size());
    }

    @Test
    public void testUpdateRestaurantStars() {

        restaurant1.updateRestaurantStars(5);
        assertEquals(5, restaurant1.getNumOfStars());

        restaurant1.updateRestaurantStars(1);
        assertEquals(3, restaurant1.getNumOfStars());

        restaurant1.updateRestaurantStars(1);
        assertEquals(2.3333333333333335, restaurant1.getNumOfStars());
    }

    @Test
    public void testToStringReview() {
        assertEquals("Review{reviewText='Delicious', author='Omar', numOfStars=5.0}",review1.toString());
        assertEquals("Review{reviewText='not bad', author='Rawzi', numOfStars=2.0}",review3.toString());
    }
}
